# Feature Engineering

---

1. Import packages
2. Load data
3. Feature engineering

---

## 1. Import packages

In [19]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

---
## 2. Load data

In [4]:
df = pd.read_csv('./clean_data_after_eda.csv')
df["date_activ"] = pd.to_datetime(df["date_activ"], format='%Y-%m-%d')
df["date_end"] = pd.to_datetime(df["date_end"], format='%Y-%m-%d')
df["date_modif_prod"] = pd.to_datetime(df["date_modif_prod"], format='%Y-%m-%d')
df["date_renewal"] = pd.to_datetime(df["date_renewal"], format='%Y-%m-%d')

In [3]:
df.head(3)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,4.100838e-05,0.000908,2.086294,99.530517,44.235794,2.086425,9.953056e+01,44.236702,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,1.217891e-03,0.000000,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.000004,9.450150e-08,0.000000,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000,0

---

## 3. Feature engineering

Remove irrelevant columns

In [5]:
cols_to_remove = ["id"]  
df = df.drop(columns=cols_to_remove)
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,0.000131,4.100838e-05,9.084737e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,0.000009,2.225451e-06,1.802667e-08,0.014939,0.005682,0.000299,0.014948,5.684001e-03,2.987132e-04,1
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,1
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0

Expand date columns

In [6]:
date_cols = ["date_activ", "date_end", "date_modif_prod", "date_renewal"]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')  
    df[f"{col}_year"] = df[col].dt.year
    df[f"{col}_month"] = df[col].dt.month
    df[f"{col}_day"] = df[col].dt.day

In [7]:
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_activ_day,date_end_year,date_end_month,date_end_day,date_modif_prod_year,date_modif_prod_month,date_modif_prod_day,date_renewal_year,date_renewal_month,date_renewal_day
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,15,2016,6,15,2015,11,1,2015,6,23
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,21,2016,8,30,2009,8,21,2015,8,31
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,16,2016,4,16,2010,4,16,2015,4,17
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,30,2016,3,30,2010,3,30,2015,3,31
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,13,2016,3,7,2010,1,13,2015,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,24,2016,5,8,2015,5,8,2014,5,26
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,27,2016,8,27,2012,8,27,2015,8,28
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,8,2016,2,7,2012,2,8,2015,2,9
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,30,2016,8,30,2012,8,30,2015,8,31
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,18,2016,12,17,2009,12,18,2015,12,21

Create additional date-based features

In [8]:
df["days_active"] = (df["date_end"] - df["date_activ"]).dt.days
df["days_to_renewal"] = (df["date_renewal"] - pd.Timestamp.now()).dt.days

In [9]:
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_end_month,date_end_day,date_modif_prod_year,date_modif_prod_month,date_modif_prod_day,date_renewal_year,date_renewal_month,date_renewal_day,days_active,days_to_renewal
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,6,15,2015,11,1,2015,6,23,1096,-3488
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,8,30,2009,8,21,2015,8,31,2566,-3419
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,4,16,2010,4,16,2015,4,17,2192,-3555
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,3,30,2010,3,30,2015,3,31,2192,-3572
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,3,7,2010,1,13,2015,3,9,2245,-3594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,5,8,2015,5,8,2014,5,26,1445,-3881
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,8,27,2012,8,27,2015,8,28,1461,-3422
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,2,7,2012,2,8,2015,2,9,1460,-3622
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,8,30,2012,8,30,2015,8,31,1461,-3419
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,12,17,2009,12,18,2015,12,21,2556,-3307

Create new features from numerical columns

In [10]:
df["cons_vs_forecast"] = df["cons_12m"] - df["forecast_cons_12m"] # Consumption differences
df["margin_to_cons_ratio"] = df["margin_net_pow_ele"] / (df["cons_12m"] + 1)  # Ratio features
df["price_sensitivity"] = df["var_6m_price_peak_var"] / (df["var_6m_price_off_peak_var"] + 1) # Price sensitivity
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_modif_prod_month,date_modif_prod_day,date_renewal_year,date_renewal_month,date_renewal_day,days_active,days_to_renewal,cons_vs_forecast,margin_to_cons_ratio,price_sensitivity
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,11,1,2015,6,23,1096,-3488,0.00,25.440000,4.100299e-05
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,8,21,2015,8,31,2566,-3419,4470.05,0.003514,1.217886e-03
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,4,16,2015,4,17,2192,-3555,496.04,0.052477,9.450116e-08
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,3,30,2015,3,31,2192,-3572,1343.96,0.019066,0.000000e+00
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,1,13,2015,3,9,2245,-3594,3979.25,0.010147,2.896728e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,5,8,2014,5,26,1445,-3881,27621.99,0.000864,0.000000e+00
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,8,27,2015,8,28,1461,-3422,6591.31,0.000000,2.225431e-06
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,2,8,2015,2,9,1460,-3622,1653.61,0.021593,2.896728e-06
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,8,30,2015,8,31,1461,-3419,111.66,0.099091,1.217886e-03
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,12,18,2015,12,21,2556,-3307,7967.59,0.001356,9.450116e-08

Difference between off-peak prices in December and January of the preceding year

In [11]:
df["price_diff_dec_jan"] = df["var_year_price_off_peak"] - df["var_6m_price_off_peak"]
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_modif_prod_day,date_renewal_year,date_renewal_month,date_renewal_day,days_active,days_to_renewal,cons_vs_forecast,margin_to_cons_ratio,price_sensitivity,price_diff_dec_jan
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,1,2015,6,23,1096,-3488,0.00,25.440000,4.100299e-05,-0.983579
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,21,2015,8,31,2566,-3419,4470.05,0.003514,1.217886e-03,-0.003015
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,16,2015,4,17,2192,-3555,496.04,0.052477,9.450116e-08,0.007664
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,30,2015,3,31,2192,-3572,1343.96,0.019066,0.000000e+00,0.006467
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,13,2015,3,9,2245,-3594,3979.25,0.010147,2.896728e-06,0.005433
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,8,2014,5,26,1445,-3881,27621.99,0.000864,0.000000e+00,0.008392
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,27,2015,8,28,1461,-3422,6591.31,0.000000,2.225431e-06,-0.001353
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,8,2015,2,9,1460,-3622,1653.61,0.021593,2.896728e-06,0.004026
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,30,2015,8,31,1461,-3419,111.66,0.099091,1.217886e-03,-0.003015
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,18,2015,12,21,2556,-3307,7967.59,0.001356,9.450116e-08,0.000002

Combine consumption and forecast to create efficiency

In [12]:
df["efficiency"] = df["cons_12m"] / (df["forecast_cons_12m"] + 1)
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_renewal_year,date_renewal_month,date_renewal_day,days_active,days_to_renewal,cons_vs_forecast,margin_to_cons_ratio,price_sensitivity,price_diff_dec_jan,efficiency
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,2015,6,23,1096,-3488,0.00,25.440000,4.100299e-05,-0.983579,0.000000
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,2015,8,31,2566,-3419,4470.05,0.003514,1.217886e-03,-0.003015,24.404294
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,2015,4,17,2192,-3555,496.04,0.052477,9.450116e-08,0.007664,11.111111
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,2015,3,31,2192,-3572,1343.96,0.019066,0.000000e+00,0.006467,6.571523
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,2015,3,9,2245,-3594,3979.25,0.010147,2.896728e-06,0.005433,9.904868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,2014,5,26,1445,-3881,27621.99,0.000864,0.000000e+00,0.008392,6.941263
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,2015,8,28,1461,-3422,6591.31,0.000000,2.225431e-06,-0.001353,11.416333
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,2015,2,9,1460,-3622,1653.61,0.021593,2.896728e-06,0.004026,9.634777
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,2015,8,31,1461,-3419,111.66,0.099091,1.217886e-03,-0.003015,6.440511
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,2015,12,21,2556,-3307,7967.59,0.001356,9.450116e-08,0.000002,11.435533

Profitability per active product

In [13]:
df["profitability_per_product"] = df["margin_net_pow_ele"] / (df["nb_prod_act"] + 1)
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_renewal_month,date_renewal_day,days_active,days_to_renewal,cons_vs_forecast,margin_to_cons_ratio,price_sensitivity,price_diff_dec_jan,efficiency,profitability_per_product
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,6,23,1096,-3488,0.00,25.440000,4.100299e-05,-0.983579,0.000000,8.480000
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,8,31,2566,-3419,4470.05,0.003514,1.217886e-03,-0.003015,24.404294,8.190000
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,4,17,2192,-3555,496.04,0.052477,9.450116e-08,0.007664,11.111111,14.300000
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,3,31,2192,-3572,1343.96,0.019066,0.000000e+00,0.006467,6.571523,15.110000
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,3,9,2245,-3594,3979.25,0.010147,2.896728e-06,0.005433,9.904868,22.455000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,5,26,1445,-3881,27621.99,0.000864,0.000000e+00,0.008392,6.941263,9.293333
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,8,28,1461,-3422,6591.31,0.000000,2.225431e-06,-0.001353,11.416333,0.000000
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,2,9,1460,-3622,1653.61,0.021593,2.896728e-06,0.004026,9.634777,19.920000
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,8,31,1461,-3419,111.66,0.099091,1.217886e-03,-0.003015,6.440511,6.540000
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,12,21,2556,-3307,7967.59,0.001356,9.450116e-08,0.000002,11.435533,5.920000

consumption into categories

In [16]:
df["consumption_category"] = pd.cut(
    df["cons_12m"], bins=[0, 5000, 20000, 50000, np.inf], labels=["Low", "Medium", "High", "Very High"]
)

In [17]:
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_renewal_day,days_active,days_to_renewal,cons_vs_forecast,margin_to_cons_ratio,price_sensitivity,price_diff_dec_jan,efficiency,profitability_per_product,consumption_category
0,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,23,1096,-3488,0.00,25.440000,4.100299e-05,-0.983579,0.000000,8.480000,NaN
1,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,31,2566,-3419,4470.05,0.003514,1.217886e-03,-0.003015,24.404294,8.190000,Low
2,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,17,2192,-3555,496.04,0.052477,9.450116e-08,0.007664,11.111111,14.300000,Low
3,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,31,2192,-3572,1343.96,0.019066,0.000000e+00,0.006467,6.571523,15.110000,Low
4,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,9,2245,-3594,3979.25,0.010147,2.896728e-06,0.005433,9.904868,22.455000,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,26,1445,-3881,27621.99,0.000864,0.000000e+00,0.008392,6.941263,9.293333,High
14602,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,28,1461,-3422,6591.31,0.000000,2.225431e-06,-0.001353,11.416333,0.000000,Medium
14603,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,9,1460,-3622,1653.61,0.021593,2.896728e-06,0.004026,9.634777,19.920000,Low
14604,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,31,1461,-3419,111.66,0.099091,1.217886e-03,-0.003015,6.440511,6.540000,Low
14605,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,21,2556,-3307,7967.59,0.001356,9.450116e-08,0.000002,11.435533,5.920000,Medium

Encode categorical variables

In [20]:
cat_cols = ["channel_sales", "has_gas"]
le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col].fillna("Unknown"))
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_renewal_day,days_active,days_to_renewal,cons_vs_forecast,margin_to_cons_ratio,price_sensitivity,price_diff_dec_jan,efficiency,profitability_per_product,consumption_category
0,4,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,23,1096,-3488,0.00,25.440000,4.100299e-05,-0.983579,0.000000,8.480000,NaN
1,0,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,31,2566,-3419,4470.05,0.003514,1.217886e-03,-0.003015,24.404294,8.190000,Low
2,4,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,17,2192,-3555,496.04,0.052477,9.450116e-08,0.007664,11.111111,14.300000,Low
3,5,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,31,2192,-3572,1343.96,0.019066,0.000000e+00,0.006467,6.571523,15.110000,Low
4,0,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,9,2245,-3594,3979.25,0.010147,2.896728e-06,0.005433,9.904868,22.455000,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,4,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,26,1445,-3881,27621.99,0.000864,0.000000e+00,0.008392,6.941263,9.293333,High
14602,4,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,28,1461,-3422,6591.31,0.000000,2.225431e-06,-0.001353,11.416333,0.000000,Medium
14603,4,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,9,1460,-3622,1653.61,0.021593,2.896728e-06,0.004026,9.634777,19.920000,Low
14604,4,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,31,1461,-3419,111.66,0.099091,1.217886e-03,-0.003015,6.440511,6.540000,Low
14605,0,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,21,2556,-3307,7967.59,0.001356,9.450116e-08,0.000002,11.435533,5.920000,Medium

Handle missing values

In [21]:
df = df.fillna(df.mean(numeric_only=True))
df = df.dropna()  
df

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,date_renewal_day,days_active,days_to_renewal,cons_vs_forecast,margin_to_cons_ratio,price_sensitivity,price_diff_dec_jan,efficiency,profitability_per_product,consumption_category
1,0,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,31,2566,-3419,4470.05,0.003514,1.217886e-03,-0.003015,24.404294,8.190000,Low
2,4,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,17,2192,-3555,496.04,0.052477,9.450116e-08,0.007664,11.111111,14.300000,Low
3,5,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,31,2192,-3572,1343.96,0.019066,0.000000e+00,0.006467,6.571523,15.110000,Low
4,0,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,9,2245,-3594,3979.25,0.010147,2.896728e-06,0.005433,9.904868,22.455000,Low
5,7,8302,0,1998,2011-12-09,2016-12-09,2015-11-01,2015-12-10,796.94,1998,...,10,1827,-3318,7505.06,0.003989,4.240480e-06,0.000003,10.404291,16.560000,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,4,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,26,1445,-3881,27621.99,0.000864,0.000000e+00,0.008392,6.941263,9.293333,High
14602,4,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,28,1461,-3422,6591.31,0.000000,2.225431e-06,-0.001353,11.416333,0.000000,Medium
14603,4,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,9,1460,-3622,1653.61,0.021593,2.896728e-06,0.004026,9.634777,19.920000,Low
14604,4,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,31,1461,-3419,111.66,0.099091,1.217886e-03,-0.003015,6.440511,6.540000,Low
14605,0,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,21,2556,-3307,7967.59,0.001356,9.450116e-08,0.000002,11.435533,5.920000,Medium

Save the processed dataset

In [ ]:
df.to_csv("processed_dataset.csv", index=False)